#!/bin/bash

echo "🔍 PowerPoint Quiz - Detailed WebSocket Logging Test"
echo "=================================================="
echo ""
echo "📋 This test will help you debug WebSocket issues with detailed logging"
echo ""
echo "🎯 Instructions:"
echo "1. Open http://localhost:3000 in your browser"
echo "2. Open Developer Tools (F12)"
echo "3. Go to Console tab"
echo "4. Follow the steps below and watch the console logs"
echo ""
echo "📊 What to look for in console:"
echo "   🚀 [App] - App initialization and WebSocket URL setup"
echo "   🔌 [WebSocket] - WebSocket connection attempts and status"
echo "   📤 [useQuiz] - Event sending attempts"
echo "   📨 [useQuiz] - Message receiving and processing"
echo "   🏠 [AdminLogin] - Room creation attempts"
echo "   🚪 [ParticipantLogin] - Room joining attempts"
echo ""
echo "🧪 Test Steps:"
echo ""
echo "STEP 1: Check WebSocket Connection"
echo "---------------------------------"
echo "1. Click '🔧 Тест WebSocket' button"
echo "2. Try connecting to 'ws://localhost:3000/ws'"
echo "3. Check console for connection logs"
echo ""
echo "STEP 2: Test Room Creation (with backend)"
echo "----------------------------------------"
echo "1. Start backend: cd backend && go run cmd/server/main.go"
echo "2. Go back to main page"
echo "3. Click 'Я организатор'"
echo "4. Click 'Создать квиз'"
echo "5. Watch console for detailed logs"
echo ""
echo "STEP 3: Test Room Joining"
echo "------------------------"
echo "1. Open another tab"
echo "2. Click 'Я участник'"
echo "3. Enter room code from step 2"
echo "4. Enter nickname"
echo "5. Click 'Присоединиться'"
echo "6. Watch console for detailed logs"
echo ""
echo "🔍 Key things to check:"
echo "- Does WebSocket connect successfully?"
echo "- Are events being sent when buttons are clicked?"
echo "- Are server responses being received?"
echo "- Are there any error messages?"
echo ""
echo "📝 Log Format Explanation:"
echo "🚀 = Initialization/Setup"
echo "🔌 = WebSocket Connection"
echo "📤 = Sending data"
echo "📨 = Receiving data"
echo "🏠 = Room operations"
echo "🚪 = Join operations"
echo "✅ = Success"
echo "❌ = Error"
echo "⚠️ = Warning"
echo "🔄 = State updates"
