services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - TLS_ENABLED=false
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped
