services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    command: ["-addr", ":8081"]          # <-- только аргументы к ENTRYPOINT
    environment:
      - TLS_ENABLED=false                # TLS терминируется на nginx-хосте
    ports:
      - "127.0.0.1:8081:8081"            # nginx ходит на localhost:8081
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8081 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks: [quiz-network]
