version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    env_file:
      - ./config.env
    ports:
      - "127.0.0.1:8081:8081"  # слушаем только локально, Nginx — спереди
    restart: unless-stopped
