services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    env_file:
      - ./config.env
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - TLS_ENABLED=false
      - WS_ADDR=:8081
      - WS_ALLOWED_ORIGINS=https://wise-dream.ru,https://www.wise-dream.ru,http://localhost:3000,http://127.0.0.1:3000
      - LOG_LEVEL=info
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz-frontend
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 20s
      timeout: 3s
      retries: 5
