version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-backend
    env_file:
      - ./config.env
    environment:
      # подстраховка, если код смотрит на старые переменные
      - PORT=8081
      - HOST=0.0.0.0
      - TLS_ENABLED=false
    ports:
      - "127.0.0.1:8081:8081"  # слушаем только локально, Nginx спереди
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz-frontend
    ports:
      - "127.0.0.1:8082:80"
    restart: unless-stopped
    depends_on:
      - backend
